script: rspec -f json my_each_spec.rb
rvm:
  - 2.1.0
notifications:
  webhooks: http://progress.flatironschool.com/submissions
cache: bundler
install: gem install rspec pry nokogiri sqlite3 simplecov rake
